In [16]:
import tensorflow as tf

tf.enable_eager_execution()

tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor([4 6], shape=(2,), dtype=int32)
tf.Tensor(25, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(b'aGVsbG8gd29ybGQ', shape=(), dtype=string)
tf.Tensor(13, shape=(), dtype=int32)


In [17]:
print(tf.add(1, 2))
print(tf.add([1, 2], [3, 4]))
print(tf.square(5))
print(tf.reduce_sum([1, 2, 3]))
print(tf.encode_base64("hello world"))

# Operator overloading is also supported
print(tf.square(2) + tf.square(3))

tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor([4 6], shape=(2,), dtype=int32)
tf.Tensor(25, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(b'aGVsbG8gd29ybGQ', shape=(), dtype=string)
tf.Tensor(13, shape=(), dtype=int32)


In [18]:
res = tf.add([[1, 2], [3, 4]], [[1, 2], [3, 4]])
print(res)
res = 10
print(res)

tf.Tensor(
[[2 4]
 [6 8]], shape=(2, 2), dtype=int32)
10


In [21]:
x = tf.random_uniform([3, 3])

print(x)

print("Is there a GPU available: "),
print(tf.test.is_gpu_available())

print("Is the Tensor on GPU #0:  "),
print(x.device.endswith('GPU:0'))

tf.Tensor(
[[0.24297035 0.10786676 0.38178384]
 [0.5656252  0.5549848  0.04548967]
 [0.887707   0.8339106  0.5320208 ]], shape=(3, 3), dtype=float32)
Is there a GPU available: 
False
Is the Tensor on GPU #0:  
False
